# -*- coding: utf-8 -*-
NEW = [
# ── GUÍAS GENERALES ──
{"slug":"quien-es-candidato-glp1","title":"¿Quién es candidato para un tratamiento con GLP-1?",
 "desc":"¿Eres candidato para un GLP-1 como Ozempic, Wegovy o Mounjaro? Criterios de IMC, diabetes y contraindicaciones que evalúa tu médico.",
 "eyebrow":"Guía general · Candidatos",
 "intro":"No todo el mundo necesita ni debe usar un GLP-1. Te explicamos qué criterios evalúa un médico para decidir si eres buen candidato.",
 "body":[
  {"h2":"Perfiles que suelen beneficiarse","ul":[
    "Personas con <strong>diabetes tipo 2</strong> que necesitan controlar la glucosa.",
    "Adultos con <strong>obesidad</strong> (IMC ≥ 30).",
    "Adultos con <strong>sobrepeso</strong> (IMC ≥ 27) y enfermedades asociadas (hipertensión, prediabetes, apnea, etc.).",
    "Personas que no han logrado resultados solo con dieta y ejercicio."]},
  {"h2":"¿Cómo se mide la candidatura?","p":["El médico valora tu IMC, tu composición corporal, tus antecedentes y tus objetivos. El índice de masa corporal es un primer filtro, pero no el único."],
   "table":{"head":["IMC","Clasificación","¿Suele considerarse?"],
     "rows":[["< 25","Peso normal","Generalmente no"],
             ["27 - 29.9","Sobrepeso","Sí, con comorbilidades"],
             ["≥ 30","Obesidad","Sí"]]}},
  {"h2":"¿Quién NO debería usarlos?","ul":[
    "Embarazo o lactancia.",
    "Antecedente personal/familiar de ciertos cánceres de tiroides (carcinoma medular) o síndrome MEN2.",
    "Antecedente de pancreatitis (valoración cuidadosa).",
    "Menores de edad sin indicación específica."]},
  {"h2":"La decisión siempre es médica","p":[
    "Ser candidato no se autodiagnostica. Un médico confirma la indicación, descarta contraindicaciones y define el medicamento y la dosis. Servicios como Clivi integran esa valoración con el tratamiento."]},
 ],
 "faqs":[("¿Necesito tener diabetes para usar un GLP-1?","No. Medicamentos como Wegovy y Saxenda están indicados para control de peso en personas sin diabetes."),
  ("¿Con qué IMC soy candidato?","En general IMC ≥ 30, o ≥ 27 con enfermedades asociadas, pero la valoración la hace el médico."),
  ("¿Puedo usarlos solo para bajar unos kilos estéticos?","No es su finalidad. Están pensados para obesidad/sobrepeso con riesgo, bajo supervisión médica."),
  ("¿Quién decide si soy candidato?","Un médico, tras evaluar tu IMC, antecedentes y objetivos.")],
 "related":[("que-son-los-medicamentos-glp1.html","¿Qué son los GLP-1?"),("como-obtener-receta-glp1.html","¿Cómo obtener una receta?"),("beneficios-y-riesgos-glp1.html","Beneficios y riesgos"),("../index.html","Comparar precios de GLP-1")]},

{"slug":"beneficios-y-riesgos-glp1","title":"Beneficios y riesgos de los medicamentos para bajar de peso",
 "desc":"Beneficios y riesgos de los GLP-1 para bajar de peso: pérdida de peso, salud metabólica, efectos secundarios y contraindicaciones. Guía equilibrada.",
 "eyebrow":"Guía general · Beneficios y riesgos",
 "intro":"Los GLP-1 ofrecen beneficios notables, pero no son inofensivos. Aquí tienes una visión equilibrada para decidir con información.",
 "body":[
  {"h2":"Beneficios principales","ul":[
    "Pérdida de peso significativa (10-22% según el medicamento).",
    "Mejor control de la glucosa y la resistencia a la insulina.",
    "Posible mejora de presión arterial, lípidos y riesgo cardiovascular.",
    "Reducción del apetito y de los antojos."]},
  {"h2":"Riesgos y efectos secundarios","ul":[
    "Molestias digestivas: náusea, estreñimiento, diarrea (sobre todo al inicio).",
    "Posible pérdida de masa muscular si no se cuida la proteína y el ejercicio.",
    "Riesgos poco frecuentes pero serios (pancreatitis, problemas de vesícula).",
    "Recuperación de peso si se suspende sin consolidar hábitos."]},
  {"h2":"¿Cómo se inclina la balanza?","p":[
    "Para personas con obesidad o diabetes, los beneficios suelen superar los riesgos cuando hay supervisión médica. En personas sin indicación clara, el balance cambia."]},
  {"info":"💡 El seguimiento médico reduce los riesgos: permite ajustar la dosis, vigilar efectos y proteger tu masa muscular."},
 ],
 "faqs":[("¿Los GLP-1 son seguros?","Tienen un perfil de seguridad conocido y manejable bajo supervisión médica, pero no están libres de efectos secundarios."),
  ("¿Cuál es el riesgo más común?","Las molestias digestivas (náusea, estreñimiento), que suelen mejorar con el tiempo y un escalado gradual."),
  ("¿Pierdo músculo con estos medicamentos?","Puede ocurrir si no consumes suficiente proteína ni haces ejercicio de fuerza."),
  ("¿Vale la pena el riesgo?","En obesidad/diabetes, generalmente sí con supervisión. La valoración es individual y médica.")],
 "related":[("que-son-los-medicamentos-glp1.html","¿Qué son los GLP-1?"),("quien-es-candidato-glp1.html","¿Quién es candidato?"),("nausea-glp1-como-manejarla.html","Cómo manejar la náusea"),("proteina-y-glp1.html","Proteína y GLP-1")]},

{"slug":"que-pasa-al-dejar-glp1","title":"¿Qué pasa cuando se deja de usar un GLP-1?",
 "desc":"Qué pasa al dejar un GLP-1 (Ozempic, Wegovy, Mounjaro): regreso del apetito, efecto rebote y cómo mantener el peso perdido.",
 "eyebrow":"Guía general · Suspensión",
 "intro":"Suspender un GLP-1 tiene consecuencias predecibles. Saber qué esperar te ayuda a planear un mantenimiento exitoso.",
 "body":[
  {"h2":"El apetito regresa","p":[
    "El efecto del medicamento sobre el hambre y la saciedad desaparece al suspenderlo. Muchas personas notan que el apetito vuelve en pocas semanas."]},
  {"h2":"El llamado efecto rebote","p":[
    "Sin cambios de hábitos consolidados, es frecuente recuperar una parte del peso perdido. No le ocurre a todos por igual ni necesariamente se recupera todo."]},
  {"h2":"Cómo minimizar la recuperación","ul":[
    "Construir hábitos de alimentación durante el tratamiento.",
    "Mantener el consumo de proteína y el entrenamiento de fuerza.",
    "Reducir la dosis de forma gradual bajo supervisión, no de golpe.",
    "Seguir con controles médicos tras suspender."]},
  {"info":"⚠️ No suspendas un GLP-1 por tu cuenta. Habla con tu médico para planear una salida ordenada."},
 ],
 "faqs":[("¿Se recupera todo el peso al dejar el GLP-1?","No necesariamente; depende de los hábitos. Es común recuperar una parte si no se consolidaron cambios."),
  ("¿Cuándo regresa el apetito?","Generalmente en las primeras semanas tras suspender, conforme baja el efecto del medicamento."),
  ("¿Puedo dejarlo de golpe?","No es recomendable; conviene reducir de forma gradual con tu médico."),
  ("¿Cómo mantengo el peso perdido?","Con alimentación adecuada, proteína, ejercicio de fuerza y seguimiento.")],
 "related":[("los-glp1-son-para-toda-la-vida.html","¿Son para toda la vida?"),("cuanto-peso-se-puede-perder-con-glp1.html","¿Cuánto peso se pierde?"),("plan-de-alimentacion-glp1.html","Plan de alimentación GLP-1"),("../index.html","Comparar precios de GLP-1")]},

# ── MOUNJARO ──
{"slug":"mounjaro-para-bajar-de-peso","title":"Mounjaro para bajar de peso: todo lo que debes saber",
 "desc":"Mounjaro para bajar de peso: cómo funciona la tirzepatida, cuánto se pierde, dosis, efectos secundarios y precio en México.",
 "eyebrow":"Mounjaro · Pérdida de peso",
 "intro":"Mounjaro se ha vuelto sinónimo de pérdida de peso potente. Esto es lo que necesitas saber antes de considerarlo.",
 "body":[
  {"h2":"Por qué Mounjaro es tan eficaz","p":[
    "Su sustancia, la <strong>tirzepatida</strong>, actúa sobre dos receptores (GIP y GLP-1). Esa doble acción potencia la reducción del apetito y la pérdida de peso, superando en promedio a la semaglutida en estudios."]},
  {"h2":"¿Cuánto peso se pierde?","p":[
    "En ensayos clínicos, la dosis máxima (15 mg) logró una pérdida promedio del <strong>20-22% del peso corporal</strong> a las 72 semanas, combinada con dieta y ejercicio."]},
  {"h2":"Dosis y escalado","table":{"head":["Fase","Dosis semanal"],
     "rows":[["Inicio","2.5 mg"],["Mes 2","5 mg"],["Escalado","7.5 - 10 mg"],["Máximas","12.5 - 15 mg"]]}},
  {"h2":"Efectos secundarios","p":["Los más comunes son digestivos (náusea, estreñimiento, diarrea), sobre todo al subir la dosis. Suelen disminuir con el tiempo."]},
  {"h2":"Precio en México","p":["Mounjaro cuesta desde alrededor de $3,490 MXN por pluma. Compara el precio entre farmacias en GLPcompara."]},
 ],
 "faqs":[("¿Mounjaro es el mejor para bajar de peso?","En estudios muestra la mayor pérdida de peso promedio, pero la mejor opción para ti la define tu médico."),
  ("¿Cuánto peso se pierde con Mounjaro?","En promedio 20-22% del peso a dosis máxima, según los ensayos clínicos."),
  ("¿Mounjaro sirve sin diabetes?","Se usa para control de peso bajo supervisión médica."),
  ("¿Cuánto cuesta Mounjaro?","Desde alrededor de $3,490 MXN por pluma; compara en GLPcompara.")],
 "related":[("que-es-mounjaro-como-funciona.html","¿Qué es Mounjaro?"),("cuanto-peso-se-pierde-con-mounjaro.html","¿Cuánto peso se pierde con Mounjaro?"),("efectos-secundarios-mounjaro.html","Efectos secundarios de Mounjaro"),("mounjaro-precio-mexico.html","Precio de Mounjaro")]},

{"slug":"cuanto-peso-se-pierde-con-mounjaro","title":"¿Cuánto peso puedes perder con Mounjaro?",
 "desc":"Cuánto peso se pierde con Mounjaro (tirzepatida) según la dosis y los estudios clínicos, y qué factores influyen en tus resultados.",
 "eyebrow":"Mounjaro · Resultados",
 "intro":"Mounjaro lidera las cifras de pérdida de peso entre los GLP-1. Veamos qué dicen los estudios y qué puedes esperar de forma realista.",
 "body":[
  {"h2":"Cifras de los estudios clínicos","table":{"head":["Dosis","Pérdida de peso promedio"],
     "rows":[["5 mg","~15%"],["10 mg","~19%"],["15 mg","~20-22%"]]}},
  {"h2":"Progresión típica","ul":[
    "Mes 1: adaptación, descenso leve.",
    "Meses 2-4: pérdida más marcada al subir dosis.",
    "Meses 6-12: se alcanza buena parte del objetivo.",
    "Después: fase de mantenimiento."]},
  {"h2":"Qué influye en tu resultado","ul":["La dosis alcanzada.","La alimentación (proteína).","El ejercicio de fuerza.","El sueño, el estrés y la genética."]},
  {"info":"💡 Bajar 0.5-1 kg por semana es un ritmo saludable; lo demasiado rápido cuesta músculo."},
 ],
 "faqs":[("¿Cuánto se pierde con 15 mg de Mounjaro?","En promedio 20-22% del peso corporal en estudios, con dieta y ejercicio."),
  ("¿Mounjaro hace perder más que Ozempic?","Sí, en promedio, por su acción dual GIP/GLP-1."),
  ("¿Por qué no bajo tanto como otros?","Influyen dosis, alimentación, ejercicio y genética; la respuesta es individual."),
  ("¿En cuánto tiempo se ven resultados?","Cambios notorios desde el 2º-3er mes al escalar la dosis.")],
 "related":[("mounjaro-para-bajar-de-peso.html","Mounjaro para bajar de peso"),("mounjaro-vs-wegovy.html","Mounjaro vs Wegovy"),("cuanto-peso-se-puede-perder-con-glp1.html","¿Cuánto peso con GLP-1?"),("mounjaro-precio-mexico.html","Precio de Mounjaro")]},

{"slug":"efectos-secundarios-mounjaro","title":"Efectos secundarios más comunes de Mounjaro",
 "desc":"Efectos secundarios de Mounjaro (tirzepatida): náusea, estreñimiento, diarrea y cómo manejarlos. Cuándo consultar al médico.",
 "eyebrow":"Mounjaro · Efectos secundarios",
 "intro":"Como todo GLP-1, Mounjaro puede causar efectos secundarios, sobre todo digestivos. La mayoría son leves y mejoran con el tiempo.",
 "body":[
  {"h2":"Los más frecuentes","ul":["Náusea.","Estreñimiento.","Diarrea.","Disminución del apetito (efecto buscado).","Dolor abdominal leve y eructos."]},
  {"h2":"Cómo reducirlos","ul":[
    "Subir la dosis de forma gradual según indicación.",
    "Comer porciones pequeñas y evitar comidas muy grasosas.",
    "Hidratarte bien y cuidar la fibra para el estreñimiento.",
    "Evitar acostarte justo después de comer."]},
  {"h2":"Cuándo consultar al médico","ul":[
    "Dolor abdominal intenso y persistente (posible pancreatitis).",
    "Vómito o diarrea que impiden hidratarte.",
    "Signos de problemas de vesícula (dolor en costado derecho, ictericia)."]},
  {"info":"⚠️ No suspendas ni ajustes la dosis por tu cuenta; consulta a tu médico ante efectos molestos o persistentes."},
 ],
 "faqs":[("¿Cuánto duran los efectos secundarios de Mounjaro?","Suelen ser más intensos al subir la dosis y disminuir en semanas conforme el cuerpo se adapta."),
  ("¿La náusea con Mounjaro es normal?","Sí, es el efecto más común; mejora con comidas pequeñas y escalado gradual."),
  ("¿Qué efectos requieren atención médica?","Dolor abdominal intenso, vómito/diarrea que impiden hidratarse o signos de vesícula."),
  ("¿Puedo prevenir el estreñimiento?","Ayuda la hidratación, la fibra y la actividad física.")],
 "related":[("nausea-glp1-como-manejarla.html","Cómo manejar la náusea"),("evitar-molestias-gastrointestinales-glp1.html","Evitar molestias digestivas"),("que-comer-con-mounjaro.html","Qué comer con Mounjaro"),("que-es-mounjaro-como-funciona.html","¿Qué es Mounjaro?")]},

{"slug":"que-comer-con-mounjaro","title":"¿Qué comer mientras usas Mounjaro?",
 "desc":"Qué comer con Mounjaro: alimentación rica en proteína, qué evitar para reducir náusea y cómo conservar músculo durante el tratamiento.",
 "eyebrow":"Mounjaro · Alimentación",
 "intro":"Mounjaro reduce el apetito, así que cada bocado cuenta. Comer bien maximiza resultados y minimiza molestias.",
 "body":[
  {"h2":"Prioriza la proteína","p":["Con menos apetito, es clave asegurar proteína suficiente para conservar masa muscular: huevo, pollo, pescado, lácteos, legumbres."]},
  {"h2":"Qué favorecer","ul":["Verduras y fibra para la digestión.","Grasas saludables en cantidades moderadas.","Comidas pequeñas y frecuentes.","Mucha agua."]},
  {"h2":"Qué limitar","ul":["Comidas muy grasosas o fritas (aumentan la náusea).","Exceso de azúcar y ultraprocesados.","Alcohol.","Porciones grandes de una sola vez."]},
  {"info":"💡 Una buena regla: llena primero la mitad del plato con proteína y verduras antes que con carbohidratos."},
 ],
 "faqs":[("¿Cuánta proteína debo comer con Mounjaro?","Depende de tu peso y objetivo; tu médico o nutriólogo te dará la cantidad. La proteína protege el músculo."),
  ("¿Qué alimentos empeoran la náusea?","Los muy grasosos, fritos o porciones grandes. Mejor comidas pequeñas y ligeras."),
  ("¿Puedo tomar alcohol con Mounjaro?","Mejor limitarlo; puede aumentar molestias y aportar calorías vacías."),
  ("¿Debo seguir una dieta específica?","Un plan personalizado mejora resultados; servicios como Clivi lo incluyen.")],
 "related":[("plan-de-alimentacion-glp1.html","Plan de alimentación GLP-1"),("proteina-y-glp1.html","Proteína y GLP-1"),("efectos-secundarios-mounjaro.html","Efectos secundarios de Mounjaro"),("mounjaro-para-bajar-de-peso.html","Mounjaro para bajar de peso")]},

# ── WEGOVY ──
{"slug":"cuanto-peso-se-pierde-con-wegovy","title":"¿Cuánto peso se pierde con Wegovy?",
 "desc":"Cuánto peso se pierde con Wegovy (semaglutida 2.4 mg) según los estudios, resultados a 3, 6 y 12 meses y factores que influyen.",
 "eyebrow":"Wegovy · Resultados",
 "intro":"Wegovy está aprobado específicamente para el control de peso. Veamos cuánto se pierde y en qué plazos.",
 "body":[
  {"h2":"Cifra de referencia","p":["En el estudio principal, los pacientes perdieron en promedio <strong>15-17% de su peso corporal</strong> a las 68 semanas con la dosis de 2.4 mg."]},
  {"h2":"Resultados a 3, 6 y 12 meses","table":{"head":["Periodo","Pérdida aproximada"],
     "rows":[["3 meses","5-8%"],["6 meses","10-12%"],["12 meses","15-17%"]]}},
  {"h2":"Qué influye","ul":["Alcanzar la dosis de mantenimiento (2.4 mg).","La alimentación y la proteína.","El ejercicio.","La constancia."]},
  {"info":"💡 Las cifras son promedios; algunas personas pierden más y otras menos."},
 ],
 "faqs":[("¿Cuánto peso se pierde con Wegovy en 6 meses?","En promedio 10-12%, subiendo hasta 15-17% al año."),
  ("¿Wegovy hace perder más que Ozempic?","Suele lograr algo más por su dosis más alta indicada para peso."),
  ("¿Cuándo se ven los primeros resultados?","En las primeras semanas baja el apetito; la pérdida marcada llega al escalar la dosis."),
  ("¿Se mantiene el peso al dejarlo?","Suele recuperarse parte si no se mantienen hábitos.")],
 "related":[("que-es-wegovy-como-ayuda-bajar-de-peso.html","¿Qué es Wegovy?"),("efectos-secundarios-wegovy.html","Efectos secundarios de Wegovy"),("wegovy-vs-ozempic.html","Wegovy vs Ozempic"),("wegovy-precio-mexico.html","Precio de Wegovy")]},

{"slug":"efectos-secundarios-wegovy","title":"Efectos secundarios de Wegovy y cómo manejarlos",
 "desc":"Efectos secundarios de Wegovy (semaglutida): náusea, estreñimiento y molestias digestivas, cómo manejarlos y cuándo consultar al médico.",
 "eyebrow":"Wegovy · Efectos secundarios",
 "intro":"Wegovy comparte los efectos secundarios típicos de los GLP-1. La buena noticia: la mayoría son manejables y temporales.",
 "body":[
  {"h2":"Los más comunes","ul":["Náusea.","Estreñimiento o diarrea.","Dolor abdominal leve.","Fatiga al inicio.","Reflujo o eructos."]},
  {"h2":"Cómo manejarlos","ul":[
    "Respetar el escalado gradual de la dosis.",
    "Comer porciones pequeñas, bajas en grasa.",
    "Hidratación y fibra para el estreñimiento.",
    "No acostarse justo después de comer."]},
  {"h2":"Señales de alarma","ul":["Dolor abdominal intenso y persistente.","Vómito/diarrea que impiden hidratarse.","Dolor en costado derecho o ictericia."]},
 ],
 "faqs":[("¿La náusea con Wegovy desaparece?","Suele disminuir tras las primeras semanas y con cada escalón de dosis."),
  ("¿Cómo evito el estreñimiento?","Con agua, fibra y actividad física; tu médico puede recomendar apoyo."),
  ("¿Qué hago si los efectos son fuertes?","Consulta a tu médico; quizá ajuste el ritmo de escalado. No suspendas por tu cuenta."),
  ("¿Wegovy causa fatiga?","Puede ocurrir al inicio o si comes muy poco; cuida la proteína y la hidratación.")],
 "related":[("nausea-glp1-como-manejarla.html","Cómo manejar la náusea"),("evitar-molestias-gastrointestinales-glp1.html","Evitar molestias digestivas"),("que-es-wegovy-como-ayuda-bajar-de-peso.html","¿Qué es Wegovy?"),("cuanto-peso-se-pierde-con-wegovy.html","¿Cuánto peso con Wegovy?")]},

{"slug":"quien-puede-usar-wegovy","title":"¿Quién puede usar Wegovy?",
 "desc":"Quién puede usar Wegovy: criterios de IMC, indicaciones para control de peso y contraindicaciones. Qué evalúa tu médico antes de recetarlo.",
 "eyebrow":"Wegovy · Candidatos",
 "intro":"Wegovy está aprobado para el control de peso, pero no es para todos. Estos son los criterios habituales.",
 "body":[
  {"h2":"Indicaciones típicas","ul":[
    "Adultos con obesidad (IMC ≥ 30).",
    "Adultos con sobrepeso (IMC ≥ 27) y al menos una enfermedad asociada.",
    "Como apoyo a dieta y ejercicio, no en lugar de ellos."]},
  {"h2":"Contraindicaciones","ul":[
    "Embarazo o lactancia.",
    "Antecedente personal/familiar de carcinoma medular de tiroides o MEN2.",
    "Antecedente de pancreatitis (valoración).",
    "Alergia a la semaglutida."]},
  {"h2":"Qué valora el médico","p":["Tu IMC, antecedentes, otros medicamentos y objetivos. La receta y el seguimiento son obligatorios."]},
 ],
 "faqs":[("¿Puedo usar Wegovy sin diabetes?","Sí, está indicado para control de peso con o sin diabetes."),
  ("¿Con qué IMC puedo usar Wegovy?","Generalmente ≥ 30, o ≥ 27 con enfermedades asociadas."),
  ("¿Wegovy se puede usar en el embarazo?","No; está contraindicado en embarazo y lactancia."),
  ("¿Necesito receta para Wegovy?","Sí, siempre.")],
 "related":[("que-es-wegovy-como-ayuda-bajar-de-peso.html","¿Qué es Wegovy?"),("quien-es-candidato-glp1.html","¿Quién es candidato a GLP-1?"),("como-obtener-receta-glp1.html","¿Cómo obtener receta?"),("wegovy-precio-mexico.html","Precio de Wegovy")]},

# ── OZEMPIC ──
{"slug":"ozempic-sin-diabetes","title":"Ozempic para personas sin diabetes: lo que debes saber",
 "desc":"Ozempic para personas sin diabetes: ¿es seguro usarlo para bajar de peso?, qué dice la evidencia y alternativas aprobadas como Wegovy.",
 "eyebrow":"Ozempic · Sin diabetes",
 "intro":"Muchas personas sin diabetes usan Ozempic para bajar de peso. Esto es lo que conviene saber antes de hacerlo.",
 "body":[
  {"h2":"Lo importante primero","p":[
    "Ozempic está <strong>aprobado para diabetes tipo 2</strong>. Su uso para bajar de peso en personas sin diabetes es 'off-label' (fuera de indicación), algo que se hace con frecuencia bajo supervisión médica."]},
  {"h2":"¿Funciona sin diabetes?","p":[
    "Sí: la semaglutida reduce el apetito independientemente de la diabetes. Para control de peso, la versión específicamente aprobada (misma sustancia, dosis mayor) es <strong>Wegovy</strong>."]},
  {"h2":"Consideraciones","ul":[
    "Debe indicarlo y supervisarlo un médico.",
    "Mismos efectos secundarios digestivos.",
    "Conviene valorar si Wegovy o Mounjaro encajan mejor.",
    "No sustituye hábitos: alimentación y ejercicio siguen siendo clave."]},
 ],
 "faqs":[("¿Es seguro usar Ozempic sin diabetes?","Se usa bajo supervisión médica; el médico valora beneficios y riesgos en tu caso."),
  ("¿Ozempic o Wegovy si no tengo diabetes?","Wegovy está específicamente aprobado para peso; ambos son semaglutida. Lo decide tu médico."),
  ("¿Necesito receta aunque no tenga diabetes?","Sí, siempre se requiere receta."),
  ("¿Bajaré de peso sin dieta?","Reduce el apetito, pero los resultados son mejores con alimentación y ejercicio.")],
 "related":[("ozempic-sirve-para-bajar-de-peso.html","¿Ozempic sirve para bajar de peso?"),("wegovy-vs-ozempic.html","Wegovy vs Ozempic"),("efectos-secundarios-ozempic.html","Efectos secundarios de Ozempic"),("que-es-ozempic-para-que-sirve.html","¿Qué es Ozempic?")]},

{"slug":"efectos-secundarios-ozempic","title":"Efectos secundarios de Ozempic",
 "desc":"Efectos secundarios de Ozempic (semaglutida): náusea, estreñimiento, reflujo y cómo reducirlos. Señales que requieren atención médica.",
 "eyebrow":"Ozempic · Efectos secundarios",
 "intro":"Ozempic suele tolerarse bien, pero conviene conocer sus efectos secundarios y cómo reducirlos.",
 "body":[
  {"h2":"Los más comunes","ul":["Náusea (el más frecuente).","Estreñimiento o diarrea.","Reflujo y eructos.","Disminución del apetito.","Fatiga leve al inicio."]},
  {"h2":"Cómo reducirlos","ul":["Escalado gradual de la dosis.","Comidas pequeñas y bajas en grasa.","Hidratación y fibra.","Evitar acostarse tras comer."]},
  {"h2":"Cuándo buscar atención médica","ul":["Dolor abdominal intenso y persistente.","Vómito/diarrea severos.","Dolor en costado derecho o ictericia."]},
  {"info":"⚠️ No ajustes la dosis por tu cuenta; coméntale a tu médico cualquier efecto persistente."},
 ],
 "faqs":[("¿La náusea con Ozempic se quita?","Suele mejorar tras las primeras semanas y con escalado gradual."),
  ("¿Ozempic causa estreñimiento?","Puede; ayuda la hidratación, la fibra y el movimiento."),
  ("¿Qué efectos son de alarma?","Dolor abdominal intenso, vómito severo o signos de vesícula."),
  ("¿Debo dejar Ozempic si me cae mal?","Consulta a tu médico antes; quizá ajuste el ritmo de la dosis.")],
 "related":[("nausea-glp1-como-manejarla.html","Cómo manejar la náusea"),("alimentos-evitar-con-ozempic.html","Alimentos a evitar con Ozempic"),("que-es-ozempic-para-que-sirve.html","¿Qué es Ozempic?"),("evitar-molestias-gastrointestinales-glp1.html","Evitar molestias digestivas")]},

{"slug":"alimentos-evitar-con-ozempic","title":"¿Qué alimentos evitar cuando usas Ozempic?",
 "desc":"Qué alimentos evitar con Ozempic para reducir náusea y mejorar resultados: frituras, azúcar, alcohol y porciones grandes. Qué comer en su lugar.",
 "eyebrow":"Ozempic · Alimentación",
 "intro":"Algunos alimentos empeoran las molestias de Ozempic y frenan tus resultados. Estos son los que conviene limitar.",
 "body":[
  {"h2":"Alimentos a limitar","ul":[
    "<strong>Frituras y comidas muy grasosas</strong>: aumentan la náusea y se digieren lento.",
    "<strong>Azúcar y ultraprocesados</strong>: aportan calorías vacías y antojos.",
    "<strong>Alcohol</strong>: irrita el estómago y suma calorías.",
    "<strong>Porciones grandes</strong>: con la digestión más lenta, caen pesadas.",
    "<strong>Bebidas gaseosas</strong>: empeoran la distensión y los eructos."]},
  {"h2":"Qué comer en su lugar","ul":["Proteínas magras (pollo, pescado, huevo).","Verduras y fibra.","Grasas saludables en porciones moderadas.","Comidas pequeñas y frecuentes."]},
  {"info":"💡 Comer despacio y en porciones pequeñas reduce mucho la náusea con Ozempic."},
 ],
 "faqs":[("¿Por qué la comida grasosa me cae mal con Ozempic?","Porque el medicamento retrasa el vaciamiento del estómago y la grasa lo hace aún más lento."),
  ("¿Puedo tomar alcohol con Ozempic?","Mejor limitarlo: irrita el estómago y aporta calorías vacías."),
  ("¿Debo evitar los carbohidratos?","No del todo; prioriza proteína y verdura y modera azúcares y ultraprocesados."),
  ("¿Comer poco ayuda con la náusea?","Sí, porciones pequeñas y frecuentes reducen las molestias.")],
 "related":[("efectos-secundarios-ozempic.html","Efectos secundarios de Ozempic"),("plan-de-alimentacion-glp1.html","Plan de alimentación GLP-1"),("proteina-y-glp1.html","Proteína y GLP-1"),("ozempic-sirve-para-bajar-de-peso.html","¿Ozempic sirve para bajar de peso?")]},

{"slug":"cuanto-tarda-ozempic-en-hacer-efecto","title":"¿Cuánto tiempo tarda Ozempic en hacer efecto?",
 "desc":"Cuánto tarda Ozempic en hacer efecto: cuándo baja el apetito, cuándo se nota la pérdida de peso y por qué la dosis se sube de forma gradual.",
 "eyebrow":"Ozempic · Tiempos",
 "intro":"Ozempic no actúa de la noche a la mañana. Te explicamos cuándo empieza a notarse y por qué.",
 "body":[
  {"h2":"El apetito: primeras semanas","p":["Muchas personas notan menos apetito en los primeros días o semanas, aunque el efecto pleno llega al subir la dosis."]},
  {"h2":"La pérdida de peso: 8-12 semanas","p":["La pérdida de peso significativa suele aparecer entre la semana 8 y la 12, conforme se alcanza una dosis efectiva."]},
  {"h2":"Por qué la dosis sube poco a poco","table":{"head":["Semana","Dosis"],
     "rows":[["1-4","0.25 mg"],["5-8","0.5 mg"],["9+","1 mg (según indicación)"]]}},
  {"info":"💡 La paciencia es parte del tratamiento: subir rápido la dosis aumenta la náusea sin acelerar resultados."},
 ],
 "faqs":[("¿Cuándo empieza a hacer efecto Ozempic?","El apetito puede bajar en las primeras semanas; la pérdida de peso clara, hacia las 8-12 semanas."),
  ("¿Por qué no bajo de peso el primer mes?","Porque se usa la dosis más baja para que el cuerpo se adapte."),
  ("¿Puedo subir la dosis más rápido?","No por tu cuenta; el escalado lo define tu médico para reducir efectos."),
  ("¿Cuánto dura una pluma de Ozempic?","En general cubre unas 4 semanas según la dosis.")],
 "related":[("que-es-ozempic-para-que-sirve.html","¿Qué es Ozempic?"),("por-que-no-bajo-de-peso-con-ozempic.html","¿Por qué no bajo con Ozempic?"),("ozempic-sirve-para-bajar-de-peso.html","¿Ozempic sirve para bajar de peso?"),("ozempic-precio-mexico.html","Precio de Ozempic")]},

# ── COMPARATIVAS ──
{"slug":"ozempic-vs-saxenda","title":"Ozempic vs Saxenda: ¿cuál elegir?",
 "desc":"Ozempic vs Saxenda: diferencias de sustancia, frecuencia (semanal vs diaria), eficacia para bajar de peso y precio en México.",
 "eyebrow":"Comparativa · Ozempic vs Saxenda",
 "intro":"Ozempic y Saxenda son GLP-1, pero con diferencias clave en sustancia, frecuencia y resultados. Comparémoslos.",
 "body":[
  {"h2":"Sustancia y frecuencia","p":["<strong>Ozempic</strong> es semaglutida de aplicación semanal. <strong>Saxenda</strong> es liraglutida de aplicación diaria."]},
  {"h2":"Comparación rápida","table":{"head":["","Ozempic","Saxenda"],
     "rows":[["Sustancia","Semaglutida","Liraglutida"],
             ["Aplicación","Semanal","Diaria"],
             ["Indicación","Diabetes tipo 2","Control de peso"],
             ["Pérdida de peso","10-15%","6-8%"],
             ["Precio desde","$2,890","$1,990"]]}},
  {"h2":"¿Cuál elegir?","p":[
    "Ozempic suele dar más pérdida de peso y la comodidad de una sola aplicación semanal. Saxenda tiene un precio de entrada más bajo pero requiere inyección diaria. La decisión es médica."]},
 ],
 "faqs":[("¿Ozempic es mejor que Saxenda para bajar de peso?","En promedio sí, y es semanal en vez de diario, pero depende de tu caso."),
  ("¿Saxenda es más barata?","Tiene un precio de entrada por pluma más bajo, pero se aplica a diario."),
  ("¿Cada cuánto se aplica cada una?","Ozempic una vez por semana; Saxenda una vez al día."),
  ("¿Ambas necesitan receta?","Sí.")],
 "related":[("que-es-ozempic-para-que-sirve.html","¿Qué es Ozempic?"),("mounjaro-vs-ozempic.html","Mounjaro vs Ozempic"),("mejor-medicamento-para-bajar-de-peso-2026.html","Mejor medicamento 2026"),("../index.html","Comparar precios de GLP-1")]},

{"slug":"cambiar-de-ozempic-a-mounjaro","title":"¿Vale la pena cambiar de Ozempic a Mounjaro?",
 "desc":"¿Cambiar de Ozempic a Mounjaro? Cuándo tiene sentido, qué esperar en resultados y efectos, y por qué la decisión debe ser médica.",
 "eyebrow":"Comparativa · Cambio de tratamiento",
 "intro":"Si Ozempic ya no te da resultados o te estancaste, quizá te preguntes si cambiar a Mounjaro. Veamos cuándo tiene sentido.",
 "body":[
  {"h2":"Por qué algunos consideran el cambio","ul":[
    "Estancamiento de peso con Ozempic.",
    "Buscar mayor pérdida de peso (Mounjaro suele lograr más).",
    "Tolerancia o respuesta insuficiente."]},
  {"h2":"Qué esperar","p":[
    "Mounjaro (tirzepatida) añade la acción sobre el receptor GIP, lo que en estudios se traduce en mayor pérdida de peso. Al cambiar, se reinicia el escalado de dosis para reducir efectos secundarios."]},
  {"h2":"Consideraciones","ul":[
    "El precio de entrada de Mounjaro es algo mayor.",
    "Pueden reaparecer molestias digestivas al reescalar.",
    "El cambio debe valorarlo y supervisarlo tu médico."]},
  {"info":"⚠️ No cambies de medicamento por tu cuenta. La transición la define tu médico según tu respuesta y tolerancia."},
 ],
 "faqs":[("¿Mounjaro funciona mejor que Ozempic?","En promedio logra mayor pérdida de peso, pero la respuesta es individual."),
  ("¿Tengo que reiniciar la dosis al cambiar?","Sí, se suele empezar por la dosis baja de Mounjaro y escalar."),
  ("¿Es más caro Mounjaro?","Su precio de entrada suele ser algo mayor que el de Ozempic."),
  ("¿Quién decide el cambio?","Tu médico, según tu evolución y tolerancia.")],
 "related":[("mounjaro-vs-ozempic.html","Mounjaro vs Ozempic"),("por-que-no-bajo-de-peso-con-ozempic.html","¿Por qué no bajo con Ozempic?"),("semaglutida-vs-tirzepatida.html","Semaglutida vs Tirzepatida"),("mounjaro-precio-mexico.html","Precio de Mounjaro")]},

# ── NUTRICIÓN Y HÁBITOS ──
{"slug":"plan-de-alimentacion-glp1","title":"El mejor plan de alimentación durante un tratamiento GLP-1",
 "desc":"El mejor plan de alimentación con GLP-1: prioridad a la proteína, fibra e hidratación para maximizar la pérdida de peso y conservar músculo.",
 "eyebrow":"Nutrición · Plan de alimentación",
 "intro":"El medicamento reduce el apetito; la alimentación decide la calidad de tus resultados. Este es el marco que mejor funciona con GLP-1.",
 "body":[
  {"h2":"Los 4 pilares","ul":[
    "<strong>Proteína primero</strong>: protege la masa muscular cuando comes menos.",
    "<strong>Verduras y fibra</strong>: saciedad y digestión.",
    "<strong>Carbohidratos de calidad</strong> en porciones moderadas.",
    "<strong>Hidratación</strong>: fundamental para evitar estreñimiento."]},
  {"h2":"Cómo armar el plato","p":["Llena la mitad con verduras, un cuarto con proteína y un cuarto con carbohidratos de calidad. Empieza por la proteína y la verdura."]},
  {"h2":"Ejemplo de día","table":{"head":["Comida","Ejemplo"],
     "rows":[["Desayuno","Huevos + verduras + fruta"],
             ["Comida","Pollo/pescado + ensalada + arroz integral"],
             ["Cena","Proteína magra + verduras al vapor"],
             ["Snacks","Yogur griego, nueces, fruta"]]}},
  {"info":"💡 Con poco apetito, prioriza nutrir antes que 'llenar'. Un plan personalizado (como el de Clivi) se ajusta a ti."},
 ],
 "faqs":[("¿Cuánta proteína necesito con un GLP-1?","Suficiente para conservar músculo; tu nutriólogo la calcula según tu peso y objetivo."),
  ("¿Puedo comer carbohidratos?","Sí, de calidad y en porciones moderadas."),
  ("¿Por qué tanta agua?","Reduce el estreñimiento, frecuente con los GLP-1, y apoya la digestión."),
  ("¿Necesito un plan personalizado?","Mejora mucho los resultados; servicios como Clivi lo incluyen.")],
 "related":[("proteina-y-glp1.html","Proteína y GLP-1"),("que-comer-con-mounjaro.html","Qué comer con Mounjaro"),("alimentos-evitar-con-ozempic.html","Alimentos a evitar con Ozempic"),("../index.html","Comparar precios de GLP-1")]},

{"slug":"proteina-y-glp1","title":"Proteína y GLP-1: por qué son una combinación clave",
 "desc":"Por qué la proteína es clave durante un tratamiento GLP-1: conserva masa muscular, aumenta la saciedad y mejora la calidad de la pérdida de peso.",
 "eyebrow":"Nutrición · Proteína",
 "intro":"Si solo cuidas una cosa en tu alimentación durante un GLP-1, que sea la proteína. Esta es la razón.",
 "body":[
  {"h2":"Por qué importa tanto","p":[
    "Al reducir la ingesta, el cuerpo puede perder grasa <em>y</em> músculo. La proteína suficiente ayuda a que la pérdida sea sobre todo de grasa, conservando la masa muscular."]},
  {"h2":"Beneficios de la proteína con GLP-1","ul":[
    "Conserva masa muscular y metabolismo.",
    "Aumenta la saciedad (se suma al efecto del medicamento).",
    "Apoya la recuperación si entrenas fuerza.",
    "Mejora la composición corporal final."]},
  {"h2":"Buenas fuentes","ul":["Huevo, pollo, pavo, pescado.","Lácteos (yogur griego, queso cottage).","Legumbres y tofu.","Suplementos de proteína si te cuesta llegar."]},
  {"info":"💡 Reparte la proteína entre comidas: el cuerpo la aprovecha mejor que en una sola toma grande."},
 ],
 "faqs":[("¿Por qué pierdo músculo con un GLP-1?","Porque al comer menos, sin suficiente proteína y ejercicio, parte de la pérdida puede ser muscular."),
  ("¿Cuánta proteína debo comer?","Depende de tu peso y objetivo; un profesional la calcula. Suele ser más de lo que se cree."),
  ("¿Sirven los suplementos de proteína?","Sí, son útiles cuando el apetito reducido dificulta llegar a la meta con comida."),
  ("¿La proteína ayuda con el apetito?","Sí, aumenta la saciedad y complementa el efecto del medicamento.")],
 "related":[("plan-de-alimentacion-glp1.html","Plan de alimentación GLP-1"),("que-comer-con-mounjaro.html","Qué comer con Mounjaro"),("beneficios-y-riesgos-glp1.html","Beneficios y riesgos"),("../index.html","Comparar precios de GLP-1")]},

# ── EFECTOS SECUNDARIOS ──
{"slug":"nausea-glp1-como-manejarla","title":"Náusea con Ozempic, Wegovy o Mounjaro: cómo manejarla",
 "desc":"Cómo manejar la náusea con GLP-1 (Ozempic, Wegovy, Mounjaro): causas, consejos prácticos de alimentación y cuándo consultar al médico.",
 "eyebrow":"Efectos secundarios · Náusea",
 "intro":"La náusea es el efecto secundario más común de los GLP-1. La buena noticia: suele ser temporal y manejable.",
 "body":[
  {"h2":"Por qué ocurre","p":["Los GLP-1 retrasan el vaciamiento del estómago y actúan sobre el centro del apetito; eso puede provocar náusea, sobre todo al iniciar o subir la dosis."]},
  {"h2":"Cómo reducirla","ul":[
    "Comer porciones pequeñas y frecuentes.",
    "Evitar frituras, grasas y comidas muy condimentadas.",
    "Comer despacio y no acostarte después.",
    "Hidratarte a sorbos; el jengibre puede ayudar.",
    "Respetar el escalado gradual de dosis."]},
  {"h2":"Cuándo consultar","ul":["Náusea con vómito que impide hidratarte.","Dolor abdominal intenso y persistente.","Pérdida de peso demasiado rápida o debilidad marcada."]},
  {"info":"💡 La náusea suele ser peor los primeros días tras cada aumento de dosis y luego mejora."},
 ],
 "faqs":[("¿Cuánto dura la náusea con los GLP-1?","Suele durar pocos días tras iniciar o subir la dosis y mejorar después."),
  ("¿Qué comer si tengo náusea?","Comidas ligeras, pequeñas y bajas en grasa; evita frituras y olores fuertes."),
  ("¿La náusea significa que debo dejar el medicamento?","No necesariamente; coméntalo con tu médico, que puede ajustar el ritmo de dosis."),
  ("¿El jengibre ayuda?","A muchas personas sí, junto con hidratarse a sorbos.")],
 "related":[("evitar-molestias-gastrointestinales-glp1.html","Evitar molestias digestivas"),("efectos-secundarios-ozempic.html","Efectos secundarios de Ozempic"),("efectos-secundarios-mounjaro.html","Efectos secundarios de Mounjaro"),("efectos-secundarios-wegovy.html","Efectos secundarios de Wegovy")]},

{"slug":"evitar-molestias-gastrointestinales-glp1","title":"Cómo evitar molestias gastrointestinales con un GLP-1",
 "desc":"Cómo evitar molestias gastrointestinales con GLP-1: estreñimiento, diarrea y reflujo. Hábitos de alimentación e hidratación que ayudan.",
 "eyebrow":"Efectos secundarios · Digestión",
 "intro":"Más allá de la náusea, los GLP-1 pueden causar estreñimiento, diarrea o reflujo. Estos hábitos reducen las molestias.",
 "body":[
  {"h2":"Para el estreñimiento","ul":["Aumenta la fibra (verduras, fruta, granos integrales).","Toma suficiente agua.","Muévete a diario; el ejercicio ayuda al tránsito.","Consulta a tu médico si persiste."]},
  {"h2":"Para la diarrea","ul":["Evita frituras y exceso de grasa.","Hidrátate bien para reponer líquidos.","Modera la cafeína.","Si es intensa o prolongada, consulta."]},
  {"h2":"Para el reflujo y los eructos","ul":["Porciones pequeñas.","No acostarte tras comer.","Evita comidas muy grasosas y gaseosas."]},
  {"h2":"Hábitos que ayudan siempre","ul":["Comer despacio y en porciones pequeñas.","Hidratación constante.","Escalado gradual de la dosis.","Priorizar proteína y fibra."]},
 ],
 "faqs":[("¿El estreñimiento con GLP-1 es normal?","Sí, es frecuente; mejora con fibra, agua y actividad física."),
  ("¿Qué hago si tengo diarrea?","Hidrátate, evita grasas y modera la cafeína; si es intensa o prolongada, consulta."),
  ("¿Cómo evito el reflujo?","Porciones pequeñas, no acostarte tras comer y evitar grasas y gaseosas."),
  ("¿Estas molestias desaparecen?","Suelen disminuir conforme el cuerpo se adapta y con buenos hábitos.")],
 "related":[("nausea-glp1-como-manejarla.html","Cómo manejar la náusea"),("plan-de-alimentacion-glp1.html","Plan de alimentación GLP-1"),("beneficios-y-riesgos-glp1.html","Beneficios y riesgos"),("../index.html","Comparar precios de GLP-1")]},
]

# ── Estructura completa del índice (42 artículos) ──
INDEX_ALL = [
 ("Guías Generales sobre GLP-1", [
   ("que-son-los-medicamentos-glp1","¿Qué son los medicamentos GLP-1 y cómo ayudan a bajar de peso?"),
   ("cuanto-peso-se-puede-perder-con-glp1","¿Cuánto peso se puede perder con un GLP-1?"),
   ("quien-es-candidato-glp1","¿Quién es candidato para un tratamiento con GLP-1?"),
   ("beneficios-y-riesgos-glp1","Beneficios y riesgos de los medicamentos para bajar de peso"),
   ("que-pasa-al-dejar-glp1","¿Qué pasa cuando se deja de usar un GLP-1?"),
 ]),
 ("Mounjaro", [
   ("que-es-mounjaro-como-funciona","¿Qué es Mounjaro y cómo funciona?"),
   ("mounjaro-precio-mexico","¿Cuánto cuesta Mounjaro en México?"),
   ("mounjaro-para-bajar-de-peso","Mounjaro para bajar de peso: todo lo que debes saber"),
   ("cuanto-peso-se-pierde-con-mounjaro","¿Cuánto peso puedes perder con Mounjaro?"),
   ("efectos-secundarios-mounjaro","Efectos secundarios más comunes de Mounjaro"),
   ("que-comer-con-mounjaro","¿Qué comer mientras usas Mounjaro?"),
 ]),
 ("Wegovy", [
   ("que-es-wegovy-como-ayuda-bajar-de-peso","¿Qué es Wegovy y cómo ayuda a bajar de peso?"),
   ("wegovy-precio-mexico","Wegovy en México: disponibilidad y costos"),
   ("cuanto-peso-se-pierde-con-wegovy","¿Cuánto peso se pierde con Wegovy?"),
   ("efectos-secundarios-wegovy","Efectos secundarios de Wegovy y cómo manejarlos"),
   ("quien-puede-usar-wegovy","¿Quién puede usar Wegovy?"),
 ]),
 ("Ozempic", [
   ("que-es-ozempic-para-que-sirve","¿Qué es Ozempic y para qué sirve?"),
   ("ozempic-sirve-para-bajar-de-peso","¿Ozempic sirve para bajar de peso?"),
   ("ozempic-precio-mexico","¿Cuánto cuesta Ozempic en México?"),
   ("ozempic-sin-diabetes","Ozempic para personas sin diabetes: lo que debes saber"),
   ("efectos-secundarios-ozempic","Efectos secundarios de Ozempic"),
   ("alimentos-evitar-con-ozempic","¿Qué alimentos evitar cuando usas Ozempic?"),
   ("cuanto-tarda-ozempic-en-hacer-efecto","¿Cuánto tiempo tarda Ozempic en hacer efecto?"),
 ]),
 ("Comparativas", [
   ("mounjaro-vs-wegovy","Mounjaro vs Wegovy: comparación completa"),
   ("mounjaro-vs-ozempic","Mounjaro vs Ozempic: eficacia, precio y resultados"),
   ("wegovy-vs-ozempic","Wegovy vs Ozempic para pérdida de peso"),
   ("semaglutida-vs-tirzepatida","Semaglutida vs Tirzepatida: ¿cuál es mejor?"),
   ("glp1-vs-cirugia-bariatrica","GLP-1 vs cirugía bariátrica: ¿qué conviene?"),
   ("ozempic-vs-saxenda","Ozempic vs Saxenda: ¿cuál elegir?"),
   ("cambiar-de-ozempic-a-mounjaro","¿Vale la pena cambiar de Ozempic a Mounjaro?"),
 ]),
 ("Nutrición y Hábitos", [
   ("plan-de-alimentacion-glp1","El mejor plan de alimentación durante un tratamiento GLP-1"),
   ("proteina-y-glp1","Proteína y GLP-1: por qué son una combinación clave"),
 ]),
 ("Efectos Secundarios", [
   ("nausea-glp1-como-manejarla","Náusea con Ozempic, Wegovy o Mounjaro: cómo manejarla"),
   ("evitar-molestias-gastrointestinales-glp1","Cómo evitar molestias gastrointestinales"),
 ]),
 ("Temas de Alta Conversión", [
   ("cuanto-cuesta-bajar-de-peso-con-glp1-mexico","¿Cuánto cuesta bajar de peso con GLP-1 en México?"),
   ("como-obtener-receta-glp1","¿Cómo obtener una receta para medicamentos GLP-1?"),
   ("mejor-medicamento-para-controlar-el-apetito","¿Cuál es el mejor medicamento para controlar el apetito?"),
   ("mejor-medicamento-para-bajar-de-peso-2026","¿Qué medicamento para bajar de peso es mejor en 2026?"),
   ("por-que-no-bajo-de-peso-con-ozempic","¿Por qué no estoy bajando de peso con Ozempic?"),
   ("historias-de-exito-antes-y-despues-glp1","Historias de éxito: antes y después con GLP-1"),
   ("mitos-sobre-ozempic-y-wegovy","Los 10 mitos más comunes sobre Ozempic y Wegovy"),
   ("los-glp1-son-para-toda-la-vida","¿Los medicamentos para bajar de peso son para toda la vida?"),
 ]),
]
